"""v1.0.rc-4

Revision ID: 5dd3221fbfdd
Revises: dd1f9a8a2aee
Create Date: 2021-03-25 09:51:31.253009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd3221fbfdd'
down_revision = 'dd1f9a8a2aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('title', sa.String(length=128), nullable=True))

    op.drop_constraint('file_status_request_id_fkey', 'file_status', type_="foreignkey")
    op.drop_constraint('files_request_id_fkey', 'files', type_="foreignkey")
    op.drop_constraint('requests_request_id_key', 'requests', type_='unique',)
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=True)
    op.create_foreign_key(
        'file_status_request_id_fkey', 'file_status', 'requests', ['request_id'], ['request_id']
    )
    op.create_foreign_key(
        'files_request_id_fkey', 'files', 'requests', ['request_id'], ['request_id']
    )

    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub'), table_name='users')

    op.drop_constraint('file_status_request_id_fkey', 'file_status', type_="foreignkey")
    op.drop_constraint('files_request_id_fkey', 'files', type_="foreignkey")
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.create_unique_constraint('requests_request_id_key', 'requests', ['request_id'])
    op.create_foreign_key(
        'file_status_request_id_fkey', 'file_status', 'requests', ['request_id'], ['request_id']
    )
    op.create_foreign_key(
        'files_request_id_fkey', 'files', 'requests', ['request_id'], ['request_id']
    )

    op.drop_column('requests', 'title')
    # ### end Alembic commands ###
